name: pipeline

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dbt packages
        working-directory: dbt
        run: dbt deps --profiles-dir .

      - name: Ingest reference data
        run: python -m ingestion.ingest_reference

      - name: Ingest recent facts
        run: python -m ingestion.ingest_facts --lookback-days 25

      - name: Ingest recent prices
        run: python -m ingestion.ingest_prices --lookback-days 25

      - name: Build dbt models
        working-directory: dbt
        run: dbt build --profiles-dir .

      - name: Export marts to CSV
        run: PYTHONPATH=. python -m publishing.export_for_tableau
         # pwd
         # ls -la
         # python -m publishing.export_for_tableau

      - name: Upload exports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tableau-exports
          path: data/exports/*.csv

      - name: Push to Google Sheets
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID}}
        run: python -m publishing.export_to_sheets